-- DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS pointto_solution;

CREATE TABLE IF NOT EXISTS user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE IF NOT EXISTS raw_image (
  id INTEGER PRIMARY KEY,
  filename TEXT NOT NULL,
  extension TEXT NOT NULL,
  processed BOOLEAN DEFAULT FALSE,
  data BLOB NOT NULL
);

CREATE TABLE IF NOT EXISTS pointto_option (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  type TEXT NOT NULL,
  image BLOB NOT NULL
);

CREATE TABLE IF NOT EXISTS pointto_solution (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  image_id INTEGER,
  option_id INTEGER,
  user_id INTEGER
);

CREATE TABLE IF NOT EXISTS processed_image_info (
  raw_image_id INTEGER PRIMARY KEY,
  interact_block_type INTEGER NOT NULL
);
